// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ8BpidpFgXX2oD_fNra581maar5TvuvA',
    appId: '1:215337466196:web:08321cd2887be29f8770c1',
    messagingSenderId: '215337466196',
    projectId: 'fir-trial-6eaac',
    authDomain: 'fir-trial-6eaac.firebaseapp.com',
    storageBucket: 'fir-trial-6eaac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ-mjMZ5acowXv2TEMBUWj-BotCW6sujM',
    appId: '1:215337466196:android:ffec9f966eb9a4c98770c1',
    messagingSenderId: '215337466196',
    projectId: 'fir-trial-6eaac',
    storageBucket: 'fir-trial-6eaac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfr9BaT-KuiQBVcajJIQbl-dyKYAU0XPI',
    appId: '1:215337466196:ios:e4ec43053dce54ef8770c1',
    messagingSenderId: '215337466196',
    projectId: 'fir-trial-6eaac',
    storageBucket: 'fir-trial-6eaac.firebasestorage.app',
    iosBundleId: 'com.example.finalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfr9BaT-KuiQBVcajJIQbl-dyKYAU0XPI',
    appId: '1:215337466196:ios:e4ec43053dce54ef8770c1',
    messagingSenderId: '215337466196',
    projectId: 'fir-trial-6eaac',
    storageBucket: 'fir-trial-6eaac.firebasestorage.app',
    iosBundleId: 'com.example.finalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ8BpidpFgXX2oD_fNra581maar5TvuvA',
    appId: '1:215337466196:web:3bf077a4461510468770c1',
    messagingSenderId: '215337466196',
    projectId: 'fir-trial-6eaac',
    authDomain: 'fir-trial-6eaac.firebaseapp.com',
    storageBucket: 'fir-trial-6eaac.firebasestorage.app',
  );
}
